export const apiRoutes = {
  USERS_PREFIX: '/users',
  ROLES_PREFIX: '/roles',
  PERMISSIONS_PREFIX: '/permissions',
  AUCTIONS_PREFIX: '/auctions',
  BIDS_PREFIX: '/bids',
  FETCH_USER: '/auth',
  LOGIN: '/auth/login',
  SIGNUP: '/auth/register',
  SIGNOUT: '/auth/signout',
  REFRESH_TOKENS: '/auth/refresh-tokens',
  UPLOAD_AUCTION_IMAGE: '/auctions/upload',
  UPLOAD_AVATAR_IMAGE: '/users/avatar',
  USERS_MY_AUCTIONS: '/users/me/auctions',
  USERS_MY_BIDS: '/users/me/bids',
  AUCTIONS_USER: '/auctions/user',
  AUCTIONS_ADDED: '/auctions/added',
  AUCTIONS_VIEW: '/auctions/view',
  AUCTIONS_WINNING: '/auctions/winning',
  AUCTIONS_ENDING_SOON: '/auctions/ending-soon',
  AUCTIONS_RECENT: '/auctions/recent',
  BIDS_AUCTION: '/bids/auction', // Ensure this matches your backend endpoint
  BIDS_USER: '/bids/user',
  AUCTIONS_BIDDED: '/auctions/bidded',
}
